# frozen_string_literal: true

# app/helpers/user_particulars_helper.rb
module UserParticularsHelper
  def country_options
    [
      'Afghanistan', 'Åland Islands', 'Albania', 'Algeria', 'American Samoa', 'Andorra',
      'Angola', 'Anguilla', 'Antarctica', 'Antigua and Barbuda', 'Argentina', 'Armenia',
      'Aruba', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
      'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia',
      'Bosnia and Herzegovina', 'Botswana', 'Bouvet Island', 'Brazil',
      'British Indian Ocean Territory', 'Brunei Darussalam', 'Bulgaria', 'Burkina Faso',
      'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde', 'Cayman Islands',
      'Central African Republic', 'Chad', 'Chile', 'China', 'Christmas Island',
      'Cocos (Keeling) Islands', 'Colombia', 'Comoros', 'Congo', 'Congo, The Democratic Republic of The',
      'Cook Islands', 'Costa Rica', "Cote D'ivoire", 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic',
      'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador',
      'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia', 'Falkland Islands (Malvinas)',
      'Faroe Islands', 'Fiji', 'Finland', 'France', 'French Guiana', 'French Polynesia',
      'French Southern Territories', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana',
      'Gibraltar', 'Greece', 'Greenland', 'Grenada', 'Guadeloupe', 'Guam', 'Guatemala',
      'Guernsey', 'Guinea', 'Guinea-bissau', 'Guyana', 'Haiti', 'Heard Island and Mcdonald Islands',
      'Holy See (Vatican City State)', 'Honduras', 'Hong Kong', 'Hungary', 'Iceland', 'India',
      'Indonesia', 'Iran, Islamic Republic of', 'Iraq', 'Ireland', 'Isle of Man', 'Israel', 'Italy',
      'Jamaica', 'Japan', 'Jersey', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', "Korea, Democratic People's Republic of",
      'Korea, Republic of', 'Kuwait', 'Kyrgyzstan', "Lao People's Democratic Republic", 'Latvia', 'Lebanon',
      'Lesotho', 'Liberia', 'Libyan Arab Jamahiriya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macao',
      'Macedonia, The Former Yugoslav Republic of', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali',
      'Malta', 'Marshall Islands', 'Martinique', 'Mauritania', 'Mauritius', 'Mayotte', 'Mexico',
      'Micronesia, Federated States of', 'Moldova, Republic of', 'Monaco', 'Mongolia', 'Montenegro', 'Montserrat',
      'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'Netherlands Antilles',
      'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'Norfolk Island', 'Northern Mariana Islands',
      'Norway', 'Oman', 'Pakistan', 'Palau', 'Palestinian Territory, Occupied', 'Panama', 'Papua New Guinea',
      'Paraguay', 'Peru', 'Philippines', 'Pitcairn', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar',
      'Reunion', 'Romania', 'Russian Federation', 'Rwanda', 'Saint Helena', 'Saint Kitts and Nevis',
      'Saint Lucia', 'Saint Pierre and Miquelon', 'Saint Vincent and The Grenadines', 'Samoa', 'San Marino',
      'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore',
      'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Georgia and The South Sandwich Islands',
      'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Svalbard and Jan Mayen', 'Swaziland', 'Sweden', 'Switzerland',
      'Syrian Arab Republic', 'Taiwan', 'Tajikistan', 'Tanzania, United Republic of', 'Thailand', 'Timor-leste',
      'Togo', 'Tokelau', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Turks and Caicos Islands',
      'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States',
      'United States Minor Outlying Islands', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Viet Nam',
      'Virgin Islands, British', 'Virgin Islands, U.S.', 'Wallis and Futuna', 'Western Sahara', 'Yemen', 'Zambia', 'Zimbabwe'
    ]
  end

  def ethnicity_options
    [
      'Abgal',
      'Aceh',
      'Arab',
      'Arkanese, Rahkin',
      'Ashraaf, Ashraf',
      'Chin',
      'Cham',
      'Chinese, Cathay',
      'Balluchi',
      'Banadiri',
      'Burmese, Bamar, Burman',
      'Bantu',
      'Bengali',
      'Darod',
      'Dinka',
      'Fur, Forok',
      'Gurka',
      'Han',
      'Hawiye',
      'Hazara',
      'Iranian',
      'Issak',
      'Javanese',
      'Kurd',
      'Kachin',
      'Karen, Karien, Kayin',
      'Kamein/Kaman',
      'Kayah, Karenni',
      'Khmer',
      'Lisu, Lissaw',
      'Lhotshampa',
      'Majerteen',
      "Ma'adi, Madi",
      'Massalit',
      'Midgan',
      'Marehan',
      'Madiban',
      'Mon',
      'Moor',
      'Nuer',
      'Naga',
      'Palestinian',
      'Pao',
      'Panjabi',
      'Pashtun, Pushtun, Pathan, Pashto',
      'Pular, Fula',
      'Rohingya',
      'Rahan-weyn',
      'Rer-hamar',
      'Singhalese',
      'Somali',
      'Shekhal',
      'Sindhi',
      'Shan/Thai Yai',
      'Tamil',
      'Tajik',
      'Turkmen',
      'Turk',
      'Thai tribes',
      'Thai, Siamese',
      'Urdu, Muhajir',
      'Uygur',
      'Vietnamese',
      'Zaghawa',
      'Others'
    ]
  end

  def religion_options
    [
      'Ahmadiyyah',
      'Atheist/Agnostic',
      "Baha'i",
      'Buddhism',
      'Christianity',
      'Confucianism',
      'Falun Gong',
      'Hinduism',
      'Islam',
      'Jainism',
      'Judaism',
      'Shiah',
      'Shinto',
      'Sikhism',
      'Sunni',
      'Taoism',
      'No religion',
      'Unknown',
      'Others'
    ]
  end

  def country_code_options
    [
      ['Afghanistan (+93)', '+93'],
      ['Albania (+355)', '+355'],
      ['Algeria (+213)', '+213'],
      ['American Samoa (+1684)', '+1684'],
      ['Andorra (+376)', '+376'],
      ['Angola (+244)', '+244'],
      ['Anguilla (+1264)', '+1264'],
      ['Antigua and Barbuda (+1268)', '+1268'],
      ['Argentina (+54)', '+54'],
      ['Armenia (+374)', '+374'],
      ['Aruba (+297)', '+297'],
      ['Australia (+61)', '+61'],
      ['Austria (+43)', '+43'],
      ['Azerbaijan (+994)', '+994'],
      ['Bahamas (+1242)', '+1242'],
      ['Bahrain (+973)', '+973'],
      ['Bangladesh (+880)', '+880'],
      ['Barbados (+1246)', '+1246'],
      ['Belarus (+375)', '+375'],
      ['Belgium (+32)', '+32'],
      ['Belize (+501)', '+501'],
      ['Benin (+229)', '+229'],
      ['Bermuda (+1441)', '+1441'],
      ['Bhutan (+975)', '+975'],
      ['Bolivia (+591)', '+591'],
      ['Bosnia and Herzegovina (+387)', '+387'],
      ['Botswana (+267)', '+267'],
      ['Brazil (+55)', '+55'],
      ['British Virgin Islands (+1284)', '+1284'],
      ['Brunei (+673)', '+673'],
      ['Bulgaria (+359)', '+359'],
      ['Burkina Faso (+226)', '+226'],
      ['Burundi (+257)', '+257'],
      ['Cabo Verde (+238)', '+238'],
      ['Cambodia (+855)', '+855'],
      ['Cameroon (+237)', '+237'],
      ['Canada (+1)', '+1'],
      ['Cayman Islands (+1345)', '+1345'],
      ['Central African Republic (+236)', '+236'],
      ['Chad (+235)', '+235'],
      ['Chile (+56)', '+56'],
      ['China (+86)', '+86'],
      ['Colombia (+57)', '+57'],
      ['Comoros (+269)', '+269'],
      ['Congo - Brazzaville (+242)', '+242'],
      ['Congo - Kinshasa (+243)', '+243'],
      ['Cook Islands (+682)', '+682'],
      ['Costa Rica (+506)', '+506'],
      ['Croatia (+385)', '+385'],
      ['Cuba (+53)', '+53'],
      ['Curaçao (+599)', '+599'],
      ['Cyprus (+357)', '+357'],
      ['Czech Republic (+420)', '+420'],
      ['Denmark (+45)', '+45'],
      ['Djibouti (+253)', '+253'],
      ['Dominica (+1767)', '+1767'],
      ['Dominican Republic (+1-809)', '+1-809'],
      ['Dominican Republic (+1-829)', '+1-829'],
      ['Dominican Republic (+1-849)', '+1-849'],
      ['Ecuador (+593)', '+593'],
      ['Egypt (+20)', '+20'],
      ['El Salvador (+503)', '+503'],
      ['Equatorial Guinea (+240)', '+240'],
      ['Eritrea (+291)', '+291'],
      ['Estonia (+372)', '+372'],
      ['Eswatini (+268)', '+268'],
      ['Ethiopia (+251)', '+251'],
      ['Fiji (+679)', '+679'],
      ['Finland (+358)', '+358'],
      ['France (+33)', '+33'],
      ['French Guiana (+594)', '+594'],
      ['French Polynesia (+689)', '+689'],
      ['Gabon (+241)', '+241'],
      ['Gambia (+220)', '+220'],
      ['Georgia (+995)', '+995'],
      ['Germany (+49)', '+49'],
      ['Ghana (+233)', '+233'],
      ['Gibraltar (+350)', '+350'],
      ['Greece (+30)', '+30'],
      ['Greenland (+299)', '+299'],
      ['Grenada (+1473)', '+1473'],
      ['Guadeloupe (+590)', '+590'],
      ['Guam (+1671)', '+1671'],
      ['Guatemala (+502)', '+502'],
      ['Guernsey (+44-1481)', '+44-1481'],
      ['Guinea (+224)', '+224'],
      ['Guinea-Bissau (+245)', '+245'],
      ['Guyana (+592)', '+592'],
      ['Haiti (+509)', '+509'],
      ['Honduras (+504)', '+504'],
      ['Hong Kong SAR China (+852)', '+852'],
      ['Hungary (+36)', '+36'],
      ['Iceland (+354)', '+354'],
      ['India (+91)', '+91'],
      ['Indonesia (+62)', '+62'],
      ['Iran (+98)', '+98'],
      ['Iraq (+964)', '+964'],
      ['Ireland (+353)', '+353'],
      ['Isle of Man (+44-1624)', '+44-1624'],
      ['Israel (+972)', '+972'],
      ['Italy (+39)', '+39'],
      ['Jamaica (+1876)', '+1876'],
      ['Japan (+81)', '+81'],
      ['Jersey (+44-1534)', '+44-1534'],
      ['Jordan (+962)', '+962'],
      ['Kazakhstan (+7)', '+7'],
      ['Kenya (+254)', '+254'],
      ['Kiribati (+686)', '+686'],
      ['Kuwait (+965)', '+965'],
      ['Kyrgyzstan (+996)', '+996'],
      ['Laos (+856)', '+856'],
      ['Latvia (+371)', '+371'],
      ['Lebanon (+961)', '+961'],
      ['Lesotho (+266)', '+266'],
      ['Liberia (+231)', '+231'],
      ['Libya (+218)', '+218'],
      ['Liechtenstein (+423)', '+423'],
      ['Lithuania (+370)', '+370'],
      ['Luxembourg (+352)', '+352'],
      ['Macao SAR China (+853)', '+853'],
      ['Madagascar (+261)', '+261'],
      ['Malawi (+265)', '+265'],
      ['Malaysia (+60)', '+60'],
      ['Maldives (+960)', '+960'],
      ['Mali (+223)', '+223'],
      ['Malta (+356)', '+356'],
      ['Marshall Islands (+692)', '+692'],
      ['Martinique (+596)', '+596'],
      ['Mauritania (+222)', '+222'],
      ['Mauritius (+230)', '+230'],
      ['Mayotte (+262)', '+262'],
      ['Mexico (+52)', '+52'],
      ['Micronesia (+691)', '+691'],
      ['Moldova (+373)', '+373'],
      ['Monaco (+377)', '+377'],
      ['Mongolia (+976)', '+976'],
      ['Montenegro (+382)', '+382'],
      ['Montserrat (+1664)', '+1664'],
      ['Morocco (+212)', '+212'],
      ['Mozambique (+258)', '+258'],
      ['Myanmar (+95)', '+95'],
      ['Namibia (+264)', '+264'],
      ['Nauru (+674)', '+674'],
      ['Nepal (+977)', '+977'],
      ['Netherlands (+31)', '+31'],
      ['New Caledonia (+687)', '+687'],
      ['New Zealand (+64)', '+64'],
      ['Nicaragua (+505)', '+505'],
      ['Niger (+227)', '+227'],
      ['Nigeria (+234)', '+234'],
      ['Niue (+683)', '+683'],
      ['Norfolk Island (+672)', '+672'],
      ['North Korea (+850)', '+850'],
      ['North Macedonia (+389)', '+389'],
      ['Northern Mariana Islands (+1670)', '+1670'],
      ['Norway (+47)', '+47'],
      ['Oman (+968)', '+968'],
      ['Pakistan (+92)', '+92'],
      ['Palau (+680)', '+680'],
      ['Palestine (+970)', '+970'],
      ['Panama (+507)', '+507'],
      ['Papua New Guinea (+675)', '+675'],
      ['Paraguay (+595)', '+595'],
      ['Peru (+51)', '+51'],
      ['Philippines (+63)', '+63'],
      ['Poland (+48)', '+48'],
      ['Portugal (+351)', '+351'],
      ['Puerto Rico (+1)', '+1'],
      ['Qatar (+974)', '+974'],
      ['Romania (+40)', '+40'],
      ['Russia (+7)', '+7'],
      ['Rwanda (+250)', '+250'],
      ['Saint Kitts and Nevis (+1869)', '+1869'],
      ['Saint Lucia (+1758)', '+1758'],
      ['Saint Vincent and the Grenadines (+1784)', '+1784'],
      ['Samoa (+685)', '+685'],
      ['San Marino (+378)', '+378'],
      ['Sao Tome and Principe (+239)', '+239'],
      ['Saudi Arabia (+966)', '+966'],
      ['Senegal (+221)', '+221'],
      ['Serbia (+381)', '+381'],
      ['Seychelles (+248)', '+248'],
      ['Sierra Leone (+232)', '+232'],
      ['Singapore (+65)', '+65'],
      ['Sint Maarten (+1721)', '+1721'],
      ['Slovakia (+421)', '+421'],
      ['Slovenia (+386)', '+386'],
      ['Solomon Islands (+677)', '+677'],
      ['Somalia (+252)', '+252'],
      ['South Africa (+27)', '+27'],
      ['South Korea (+82)', '+82'],
      ['South Sudan (+211)', '+211'],
      ['Spain (+34)', '+34'],
      ['Sri Lanka (+94)', '+94'],
      ['Sudan (+249)', '+249'],
      ['Suriname (+597)', '+597'],
      ['Sweden (+46)', '+46'],
      ['Switzerland (+41)', '+41'],
      ['Syria (+963)', '+963'],
      ['Taiwan (+886)', '+886'],
      ['Tajikistan (+992)', '+992'],
      ['Tanzania (+255)', '+255'],
      ['Thailand (+66)', '+66'],
      ['Timor-Leste (+670)', '+670'],
      ['Togo (+228)', '+228'],
      ['Tokelau (+690)', '+690'],
      ['Tonga (+676)', '+676'],
      ['Trinidad and Tobago (+1868)', '+1868'],
      ['Tunisia (+216)', '+216'],
      ['Turkey (+90)', '+90'],
      ['Turkmenistan (+993)', '+993'],
      ['Turks and Caicos Islands (+1649)', '+1649'],
      ['Tuvalu (+688)', '+688'],
      ['Uganda (+256)', '+256'],
      ['Ukraine (+380)', '+380'],
      ['United Arab Emirates (+971)', '+971'],
      ['United Kingdom (+44)', '+44'],
      ['United States (+1)', '+1'],
      ['Uruguay (+598)', '+598'],
      ['Uzbekistan (+998)', '+998'],
      ['Vanuatu (+678)', '+678'],
      ['Vatican City (+379)', '+379'],
      ['Venezuela (+58)', '+58'],
      ['Vietnam (+84)', '+84'],
      ['Wallis and Futuna (+681)', '+681'],
      ['Yemen (+967)', '+967'],
      ['Zambia (+260)', '+260'],
      ['Zimbabwe (+263)', '+263']

    ]
  end
end
